Try building hipsparse as static library to avoid issues in cupy
Issue is:
ImportError: /user-environment/env/default/lib/libhipsparse.so.4: undefined symbol: rocsparse_destroy_spmv_descr

which is strange because:
 ldd /user-environment/env/default/lib/libhipsparse.so.4
        linux-vdso.so.1 (0x00007ffddc1c1000)
        /user-environment/env/default/lib/librocsparse.so (0x00007f6af9a27000)
 nm /user-environment/linux-zen3/rocsparse-7.1.0-qfflrfxfu2vaqu52hitvwyukdwq767rf/lib/librocsparse.so | grep rocsparse_destroy_spmv_descr
0000000002f33fc0 T rocsparse_destroy_spmv_descr